from PySide6.QtCore import QSize

BUTTON_SIZE = QSize(30, 30)
SEARCH_BOX_HEIGHT = 30
NAV_BAR_HEIGHT = 30
NAV_BAR_MIN_WIDTH = 250
NAV_BUTTON_WIDTH = 95
CLOSE_BUTTON_SIZE = QSize(35, 28)

RESULTS_MIN_WIDTH = 150
ENTRY_MIN_WIDTH = 300
SOURCES_MIN_WIDTH = 300

WINDOW_DEFAULT_WIDTH = 765
WINDOW_DEFAULT_HEIGHT = 650

SPLITTER_ENTRY_INITIAL = 400
SPLITTER_SOURCES_INITIAL = 400
SPLITTER_RESULTS_INITIAL = 200

ENTRY_LIST_WIDTH_PADDING = 60
SOURCES_FLOATING_BUTTON_SIZE = QSize(30, 30)
SOURCES_CLOSE_BUTTON_SIZE = QSize(30, 30)

NAV_SPACER_MIN_WIDTH = 5
NAV_SPACER_MAX_WIDTH = 15

LAYOUT_MARGINS = (0, 0, 0, 0)
LAYOUT_SPACING = 0
TOP_LAYOUT_SPACING = 5

NAV_BAR_CONTENTS_MARGINS = (5, 0, 5, 0)
SOURCES_SEARCH_MARGINS = (5, 0, 5, 0)
SOURCES_SEARCH_SPACING = 5
ENTRY_LAYOUT_MARGINS = (0, 0, 0, 0)
ENTRY_LAYOUT_SPACING = 0

NAV_BAR_BACKGROUND = (240, 240, 240)

FONT_FAMILY = 'Cambria', 'Times New Roman', 'Times', 'serif'
FONT_SIZE = '12pt'
FONT_WEIGHT_BOLD = 'bold'
LINE_HEIGHT = 1.4
TEXT_ALIGN = 'justify'