from PySide6.QtCore import QSize

BAR_CONTENTS_MARGINS = (5, 0, 5, 0)
BAR_SPACING = 5
BAR_HEIGHT = 30

BUTTON_SIZE = QSize(30, 30)
SEARCH_BOX_HEIGHT = 30
NAV_BUTTON_WIDTH = 95

RESULTS_MIN_WIDTH = 150
ENTRY_MIN_WIDTH = 300
SOURCES_MIN_WIDTH = 300

WINDOW_DEFAULT_WIDTH = 765
WINDOW_DEFAULT_HEIGHT = 650

SPLITTER_ENTRY_INITIAL = 400
SPLITTER_SOURCES_INITIAL = 400

ENTRY_LIST_WIDTH_PADDING = 60

NAV_SPACER_MIN_WIDTH = 5
NAV_SPACER_MAX_WIDTH = 15

DOCUMENT_MARGIN = 15

LAYOUT_MARGINS = (0, 0, 0, 0)
LAYOUT_SPACING = 0
TOP_LAYOUT_SPACING = 0
